server:
  port: 7070

spring:
  thymeleaf:
    enabled: true  
    encoding: utf-8  
    prefix: classpath:/templates/  
    cache: false  
    mode: HTML  
    suffix: .html  


  datasource:
    name: datasource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/image?serverTimezone=GMT%2B8
    username: root
    password: Lzf199201!
    type: com.alibaba.druid.pool.DruidDataSource


mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  typeAliasesPackage: top.sailliao.bing.entity            
  # type-handlers-package: test.springboot.handlers
  executor-type: SIMPLE                                   
  configuration:
    default-fetch-size: 20
    default-statement-timeout: 30